### ISSUE TITLE
DBCC Clone Database Error

### ISSUE THREAD

**Issue by way0utwest** [alex-yates-redgate/TDM-AutoMasklet#2]
I got an error with DBCC CloneDatabase. This was because I had an object in model that caused a PK error.

I resolved it with this query from Northwind_FullRestore: https://www.sqlservercentral.com/blogs/dbcc-clonedatabase-issue-duplicate-key-row-in-sys-sysschobjs

Not your issue, but something that you might keep handy for customers that get an error after line 87 runs.

**Comment by alex-yates-redgate** [comment]
Thanks for all the help Steve!

**Comment by way0utwest** [comment]
My pleasure. I'll look over the code and suggest improvements
